### PR TITLE
Fix for failing unit test

### LINKED ISSUE #112: Failing Unit Test
Description:

Currently 20 unit tests fail on bfs6.5.4.

Jenkins test report: https://jenkins.bfs.sichend.people.aws.dev/job/Kibana/job/bfs6.5.4_test/69/testReport/

### PR DESCRIPTION
**Pull request by 2samueld**
# Description:

Currently, 20 unit tests fail. These failures are related to the following:
1. API call fails when invoking uuid.v1(). Error log: (https://jenkins.bfs.sichend.people.aws.dev/job/Kibana/job/bfs6.5.4_test/69/#showFailuresLink):
```
TypeError: Cannot read property 'v1' of undefined
      146 |     const namespacePrefix =
      147 |       namespace && !this.schema.isNamespaceAgnostic(type) ? `${namespace}:` : '';
    > 148 |     return `${namespacePrefix}${type}:${id || uuid.v1()}`;
          |                                                    ^
      149 |   }
```
This PR refractors code according to [uuid documentation](https://github.com/uuidjs/uuid/blob/main/README.md#uuidv1options-buffer-offset). It first independently imports "v1" and calls the api as follows:  
```
import { v1 as uuidv1 } from 'uuid';
uuidv1();
```
**Jenkins test report**: https://jenkins.bfs.sichend.people.aws.dev/job/Kibana/job/bfs6.5.4_test/72/testReport/

Closes #112

### CODE REVIEW

File: src/server/saved_objects/serialization/index.ts [hunk 1]
```diff
@@ -22,7 +22,7 @@
  * the raw document format as stored in ElasticSearch.
  */
 
-import uuid from 'uuid';
+import { v1 as uuidv1 } from 'uuid';
```
Comment (Tengda-He) [inline src/server/saved_objects/serialization/index.ts:25]: lets add the the related errors you show in the failed jenkins job as evidence to support this change

**Review by Tengda-He — COMMENTED** [review]
add the PR related to snapshot change to support it.

File: src/server/saved_objects/serialization/index.ts (hunk 1 above)
Comment (2samueld) [reply src/server/saved_objects/serialization/index.ts:25]: Error log added

**Review by Tengda-He — APPROVED** [review]
